### ISSUE TITLE
Failures on installation

### ISSUE THREAD

**Issue by colinnewell** [cv-library/UUID4-Tiny#5]
We seem to be seeing some failures to install (or not install) due to this error.

    Undefined subroutine &main::os_unsupported called at Makefile.PL line 13.

See http://www.cpantesters.org/cpan/report/2f0fbc5a-ddeb-11e9-a65e-fe3acca03743 for an example.

**Comment by colinnewell** [comment]
Looks like we probably need ExtUtils::MakeMaker 7.26

**Comment by colinnewell** [comment]
In the attached example they had 7.24.

**Comment by jjatria** [comment]
As of #11 we require ExtUtils:MakeMaker 7.26 on our cpanfile
